version: '3.4'

services:
  maindb:
    container_name: maindb
    environment:
        SA_PASSWORD: "123jaja123"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1435:1433"

  cachedb:
    container_name: cachedb
    restart: always    
    ports:
        - "6379:6379"

  hostel.security.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings:DefaultConnection=Server=maindb;Database=Security.Api;User Id=sa;Password=qwerty1" 
      - "RedisCacheSettings:ConnectionString=localhost:6379"
    depends_on: 
      - maindb
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  hostel.catalogue.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings:DefaultConnection=Server=maindb;Database=Catalogue.Api;User Id=sa;Password=qwerty1"  
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

