version: '3.4'

services:
  masterdb:
    container_name: masterdb
    environment:
        SA_PASSWORD: "Qwerty"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  cachedb:
    container_name: cachedb
    restart: always    
    ports:
        - "6379:6379"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"

  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"  

  proxy: 
    volumes: 
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"

  client:
    ports:
      - "9000:4200"

  hostel.security.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=masterdb;Database=Security.Api;User Id=sa;Password=Qwerty" 
    depends_on: 
      - masterdb
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  hostel.catalogue.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=masterdb;Database=Catalogue.Api;User Id=sa;Password=Qwerty"  
      - "RedisCacheSettings:ConnectionString=cachedb:6379"
    depends_on: 
      - masterdb
      - cachedb
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

