version: '3.4'

services:
  masterdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  cachedb:
    image: redis:alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  client:
    image: client
    build:
      context: ../HostelBooking.Frontend
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline

  hostel.catalogue.api:
    image: ${DOCKER_REGISTRY-}hostelcatalogueapi
    build:
      context: .
      dockerfile: src/Presentation/Hostel.Catalogue.Api/Dockerfile

  hostel.security.api:
    image: ${DOCKER_REGISTRY-}hostelsecurityapi
    build:
      context: .
      dockerfile: src/Presentation/Hostel.Security.Api/Dockerfile

